name: rapido_app
description: A Flutter-based ride-sharing application that connects to the Rapido backend API.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  google_maps_flutter: ^2.2.0
  intl: ^0.20.2
  flutter_svg: ^1.1.5
  dio: ^4.0.6
  geolocator: ^9.0.2
  # Real-time features
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  # Enhanced UI
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.6.0
  # Notifications
  flutter_local_notifications: ^15.1.0+1
  # Location and maps
  geocoding: ^2.1.0
  # UI Components
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Utilities
  permission_handler: ^10.4.3
  connectivity_plus: ^4.0.2
  # Date and time
  timeago: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700